spring.application.name=marketplace
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-2.5-flash
spring.ai.retry.on-client-errors=true
spring.ai.retry.max-attempts=3
spring.ai.retry.initial-interval=1000
spring.ai.retry.multiplier=2.0
spring.data.mongodb.uri=mongodb://localhost:27017/marketplace
spring.data.mongodb.database=marketplace
socket.server.port=9090